FROM node:16 AS bulid-stage

WORKDIR /usr/src/app

COPY ./test_empty_app/package*.json .
RUN npm install

COPY ./test_empty_app/ .
RUN npm run build


FROM nginx:alpine
COPY --from=bulid-stage /usr/src/app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
